/* 源自《置身事内》单文件版 - 建筑类型定义 */
/* 自动拆分生成，请勿手动调整章节归属 */

// ============== 建筑类型定义 ==============
const BUILDING_TYPES = {
  lowRes: { name: '低层低密度住宅', cat: 'residential', shortName: '住宅', layer: 'ground', cost: 80, color: '#a8d4ef', size: 1, desc: '1-3层独栋或联排住宅，居住舒适但占地大。适合城市初期低密度开发，居民满意度较高。',
    eff: { pop: 160, jobs: 0, gdp: 10, airPol: 0.5, waterPol: 0.3, green: 0.5, edu: 0, health: 0, safety: 0, power: -5, water: -3, happiness: 2 } },
  midRes: { name: '多层中密度住宅', cat: 'residential', shortName: '住宅', layer: 'ground', cost: 250, color: '#6fb3d8', size: 1, desc: '4-7层多层住宅楼，常见于县城和郊区。性价比较高，是城市中期主力住宅形态。',
    eff: { pop: 650, jobs: 0, gdp: 35, airPol: 1.5, waterPol: 1, green: 0, edu: 0, health: 0, safety: 0, power: -15, water: -10, happiness: 0 } },
  highRes: { name: '高层高密度住宅', cat: 'residential', shortName: '住宅', layer: 'ground', cost: 600, color: '#3a8bc4', size: 1, desc: '20层以上高层塔楼，容积率极高。适合人口密集区，但居民幸福度下降，需配套公园和设施。',
    eff: { pop: 2000, jobs: 0, gdp: 100, airPol: 3, waterPol: 2, green: -0.5, edu: 0, health: 0, safety: 0, power: -40, water: -25, happiness: -3 } },
  luxuryRes: { name: '高档别墅区', cat: 'residential', shortName: '别墅', layer: 'ground', cost: 400, color: '#1e6ba8', size: 1, desc: '独栋豪华别墅，绿化率高，居住体验极佳。可吸引高收入人群，大幅提升幸福度但人口密度低。',
    eff: { pop: 110, jobs: 0, gdp: 30, airPol: 0.2, waterPol: 0.1, green: 3, edu: 1, health: 0, safety: 0, power: -8, water: -5, happiness: 8 } },
  lightInd: { name: '轻工业园区', cat: 'industrial', shortName: '工业', layer: 'ground', cost: 350, color: '#b56a18', size: 1, desc: '以加工制造、电子装配为主的轻工业区。污染较小，提供中等就业岗位，适合城市初期。',
    eff: { pop: 0, jobs: 280, gdp: 150, airPol: 8, waterPol: 5, green: -1, edu: 0, health: 0, safety: 0, power: -20, water: -15, happiness: -2 } },
  highTechInd: { name: '高新技术园区', cat: 'industrial', shortName: '科技', layer: 'ground', cost: 700, color: '#4a6fa5', size: 1, desc: '以研发、软件开发、生物医药为主的高新技术园区。GDP贡献高、污染极低，需配套高学历人才。',
    eff: { pop: 0, jobs: 350, gdp: 400, airPol: 1, waterPol: 0.5, green: 0, edu: 2, health: 0, safety: 1, power: -30, water: -10, happiness: 3 } },
  heavyInd: { name: '重工业园区', cat: 'industrial', shortName: '工业', layer: 'ground', cost: 800, color: '#964e0e', size: 1, desc: '钢铁、化工、机械等重工业基地。GDP贡献大但污染严重，需远离居民区，配套环保设施。',
    eff: { pop: 0, jobs: 800, gdp: 500, airPol: 25, waterPol: 15, green: -3, edu: 0, health: 0, safety: -2, power: -60, water: -40, happiness: -8 } },
  hazInd: { name: '危险化工业园区', cat: 'hazardous', shortName: '化工', layer: 'ground', cost: 1200, color: '#b03428', size: 1, desc: '高危化工和危险品制造区。GDP极高但有安全事故风险，严重影响周边居民健康和治安。',
    eff: { pop: 0, jobs: 550, gdp: 850, airPol: 50, waterPol: 35, green: -8, edu: 0, health: -5, safety: -8, power: -80, water: -60, happiness: -15, risk: 3 } },
  // v2.4.3: 矿区（自动生成于资源型城市周边，不可手动建造）
  mine: { name: '矿区', cat: 'industrial', shortName: '矿区', layer: 'ground', cost: 0, color: '#5a4530', size: 1, desc: '矿产资源开采区，自动生成于资源型城市周边。提供大量就业和GDP，但产值随开采逐渐衰减，最终面临资源枯竭。',
    eff: { pop: 0, jobs: 800, gdp: 600, airPol: 20, waterPol: 15, green: -5, edu: 0, health: -2, safety: -2, power: -50, water: -30, happiness: -6 }, isMining: true },
  streetCom: { name: '沿街商业', cat: 'commercial', shortName: '商业', layer: 'ground', cost: 150, color: '#e8c850', size: 1, desc: '住宅底商和沿街店铺，满足日常消费需求。投资小见效快，适合城市初期商业起步。',
    eff: { pop: 0, jobs: 70, gdp: 50, airPol: 1, waterPol: 0.5, green: 0, edu: 0, health: 0, safety: 1, power: -8, water: -5, happiness: 1 } },
  concCom: { name: '集中型商业', cat: 'commercial', shortName: '商业', layer: 'ground', cost: 500, color: '#d4a830', size: 1, desc: '集中式商业街区或小型商场，业态丰富。提供较多就业，适合中等规模城市商业中心。',
    eff: { pop: 0, jobs: 400, gdp: 250, airPol: 3, waterPol: 1.5, green: 0, edu: 0, health: 0, safety: 1, power: -25, water: -15, happiness: 2 } },
  mixCom: { name: '混合型商业', cat: 'commercial', shortName: '商业', layer: 'ground', cost: 700, color: '#c89820', size: 1, desc: '商住混合综合体，底层商业上层住宅。兼顾居住和商业，土地利用效率高。',
    eff: { pop: 280, jobs: 280, gdp: 220, airPol: 2, waterPol: 1, green: 0.5, edu: 0, health: 0, safety: 1, power: -20, water: -12, happiness: 3 } },
  plazaCom: { name: '广场型商业', cat: 'commercial', shortName: '广场', layer: 'ground', cost: 400, color: '#dcb840', size: 1, desc: '开放式商业广场，含休闲和购物功能。绿化较好，提升周边居民幸福度。',
    eff: { pop: 0, jobs: 200, gdp: 150, airPol: 1, waterPol: 0.5, green: 2, edu: 0, health: 0, safety: 2, power: -15, water: -8, happiness: 5 } },
  comStreet: { name: '商业步行街', cat: 'commercial', shortName: '商铺', layer: 'ground', cost: 600, color: '#b88810', size: 1, desc: '纯步行商业街区，禁止车辆通行。消费体验极佳，大幅提升幸福度和GDP。',
    eff: { pop: 0, jobs: 350, gdp: 300, airPol: 0.5, waterPol: 0.3, green: 1, edu: 0, health: 0, safety: 2, power: -12, water: -8, happiness: 8 } },
  comComplex: { name: '商业综合体', cat: 'commercial', shortName: '商场', layer: 'ground', cost: 1500, color: '#a87808', size: 1, desc: '大型商业综合体（万达/万象城级别），含购物、餐饮、娱乐、办公。GDP贡献极大但造价高昂。',
    eff: { pop: 150, jobs: 1000, gdp: 750, airPol: 4, waterPol: 2, green: 1, edu: 0, health: 0, safety: 2, power: -60, water: -35, happiness: 6 } },
  road: { name: '道路', cat: 'infrastructure', layer: 'ground', cost: 20, color: '#2a2a2a', size: 1, desc: '基础道路设施，连接城市各区域。所有建筑必须靠近道路才能发挥作用。是城市发展的基础。',
    eff: { pop: 0, jobs: 0, gdp: 0, airPol: 0.1, waterPol: 0, green: -0.2, edu: 0, health: 0, safety: 0, power: 0, water: 0, happiness: 0, connectivity: 1 } },
  park: { name: '公园绿地', cat: 'green', shortName: '公园', layer: 'ground', cost: 100, color: '#156028', size: 1, desc: '城市公园和绿化带，净化空气、吸收污染。大幅提升周边居民幸福度和健康水平。',
    eff: { pop: 0, jobs: 5, gdp: 5, airPol: -3, waterPol: -1, green: 10, edu: 0, health: 2, safety: 1, power: -2, water: -1, happiness: 6 } },
  elementarySchool: { name: '小学', cat: 'infrastructure', shortName: '小学', layer: 'ground', cost: 300, color: '#4a7aaa', size: 1, desc: '小学教育设施，服务周边适龄儿童。提升教育指数和居民满意度。',
    eff: { pop: 0, jobs: 40, gdp: 5, airPol: 0.3, waterPol: 0.2, green: 1, edu: 20, health: 0, safety: 1, power: -8, water: -4, happiness: 2 } },
  middleSchool: { name: '初中', cat: 'infrastructure', shortName: '初中', layer: 'ground', cost: 500, color: '#3d6491', size: 1, desc: '初级中学教育设施，提供初中阶段教育。较大幅度提升教育指数。',
    eff: { pop: 0, jobs: 60, gdp: 8, airPol: 0.4, waterPol: 0.2, green: 1, edu: 28, health: 0, safety: 1, power: -12, water: -6, happiness: 2 } },
  highSchool: { name: '高中', cat: 'infrastructure', shortName: '高中', layer: 'ground', cost: 800, color: '#30517a', size: 1, desc: '高级中学教育设施，提供高中阶段教育。大幅提升教育指数和GDP贡献。',
    eff: { pop: 0, jobs: 80, gdp: 15, airPol: 0.5, waterPol: 0.3, green: 1, edu: 40, health: 0, safety: 1, power: -15, water: -8, happiness: 3 } },
  hospital: { name: '医院', cat: 'infrastructure', shortName: '医院', layer: 'ground', cost: 800, color: '#b8283e', size: 1, desc: '综合医院，提供医疗服务。大幅提升健康指数和居民安全感，覆盖范围内居民健康保障。',
    eff: { pop: 0, jobs: 150, gdp: 30, airPol: 1, waterPol: 1, green: 0, edu: 0, health: 40, safety: 2, power: -25, water: -15, happiness: 4 } },
  university: { name: '大学', cat: 'infrastructure', shortName: '大学', layer: 'ground', cost: 3000, color: '#6d5a8c', size: 1, desc: '高等学府，大幅提升教育指数、GDP和城市声誉。需人口达10万后申报建设。', requireApproval: 'universityApproved',
    eff: { pop: 0, jobs: 200, gdp: 80, airPol: 0.5, waterPol: 0.3, green: 2, edu: 60, health: 5, safety: 2, power: -40, water: -20, happiness: 8 } },
  powerPlant: { name: '火力发电厂', cat: 'infrastructure', shortName: '电厂', layer: 'ground', cost: 1200, color: '#4a4a4a', size: 1, desc: '燃煤火力发电厂，供电量大但污染严重。造价低见效快，是基础电力来源，但空气污染和健康影响大。',
    eff: { pop: 0, jobs: 120, gdp: 60, airPol: 15, waterPol: 5, green: -2, edu: 0, health: -2, safety: 0, power: 2500, water: -20, happiness: -2 } },
  gasPower: { name: '燃气发电站', cat: 'infrastructure', shortName: '电', layer: 'ground', cost: 1500, color: '#c07f24', size: 1, desc: '天然气发电站，比燃煤清洁得多。中等供电量，污染较小，适合过渡期使用。',
    eff: { pop: 0, jobs: 80, gdp: 45, airPol: 5, waterPol: 1, green: 0, edu: 0, health: 0, safety: 0, power: 1600, water: -8, happiness: 0 } },
  cleanEnergy: { name: '风光发电站', cat: 'infrastructure', shortName: '清洁', layer: 'ground', cost: 2000, color: '#1a8a72', size: 1, desc: '风力与太阳能互补发电站。零污染、提升绿化，但造价较高、供电中等。',
    eff: { pop: 0, jobs: 60, gdp: 35, airPol: 0, waterPol: 0, green: 2, edu: 0, health: 0, safety: 0, power: 1300, water: -3, happiness: 3 } },
  solarPlant: { name: '太阳能电站', cat: 'infrastructure', shortName: '太阳能', layer: 'ground', cost: 1800, color: '#bfa02e', size: 1, desc: '大面积光伏发电阵列。零污染零水耗，但供电较低且有昼夜波动。适合日照充足地区。',
    eff: { pop: 0, jobs: 30, gdp: 20, airPol: 0, waterPol: 0, green: 1, edu: 0, health: 0, safety: 0, power: 900, water: 0, happiness: 2 } },
  windFarm: { name: '风力发电场', cat: 'infrastructure', shortName: '风电', layer: 'ground', cost: 1600, color: '#2a9d8f', size: 1, desc: '大型风力发电场。零污染但有一定噪音影响，适合郊区和沿海地区。',
    eff: { pop: 0, jobs: 40, gdp: 25, airPol: 0, waterPol: 0, green: 1, edu: 0, health: 0, safety: 0, power: 1100, water: 0, happiness: 2, noise: 5 } },
  hydroDam: { name: '水力发电站', cat: 'infrastructure', shortName: '水电', layer: 'ground', cost: 4000, color: '#3a6a9c', size: 1, desc: '水力发电大坝，兼具供水功能。供电量大且清洁，同时产水200/月，但造价高。',
    eff: { pop: 0, jobs: 100, gdp: 80, airPol: 0, waterPol: 0, green: 3, edu: 0, health: 0, safety: 0, power: 3500, water: 300, happiness: 4 } },
  nuclearPlant: { name: '核电站', cat: 'infrastructure', shortName: '核电', layer: 'ground', cost: 8000, color: '#0a6b7a', size: 1, desc: '核能发电站，单机供电能力最强。零碳排放但存在安全隐患，居民略有不安，需远离居民区。',
    eff: { pop: 0, jobs: 200, gdp: 200, airPol: 0, waterPol: 2, green: 5, edu: 0, health: 0, safety: -3, power: 8000, water: -50, happiness: -3, risk: 2 } },
  substation: { name: '变电站', cat: 'infrastructure', shortName: '变电站', layer: 'ground', cost: 200, color: '#7a5a2a', size: 1, desc: '外部接入变电站，从区域电网购电。建设成本低，但每月需按GDP比率支付购电费（约GDP的0.5%），适合电力缺口较小的城市应急使用。',
    eff: { pop: 0, jobs: 10, gdp: 5, airPol: 0, waterPol: 0, green: 0, edu: 0, health: 0, safety: 0, power: 1500, water: 0, happiness: 0 } },
  waterPump: { name: '水泵站', cat: 'infrastructure', shortName: '水泵站', layer: 'ground', cost: 400, color: '#4a7aa8', size: 1, desc: '大型增压水泵站，从远程水源抽水加压输送。供水量大，但每月需按GDP比率支付抽水运行费（约GDP的0.4%）。',
    eff: { pop: 0, jobs: 30, gdp: 10, airPol: 0, waterPol: 0, green: 0, edu: 0, health: 0, safety: 0, power: -30, water: 1200, happiness: 0 } },
  waterPlant: { name: '自来水厂', cat: 'infrastructure', shortName: '水厂', layer: 'ground', cost: 800, color: '#3a6a9c', size: 1, desc: '自来水处理厂，从水源净化并输送自来水。标准供水设施，同时净化部分水污染。',
    eff: { pop: 0, jobs: 80, gdp: 20, airPol: 0.5, waterPol: -8, green: 0, edu: 0, health: 5, safety: 0, power: -15, water: 800, happiness: 1 } },
  waterTower: { name: '水塔', cat: 'infrastructure', shortName: '水塔', layer: 'ground', cost: 300, color: '#5a86b0', size: 1, desc: '小型高位水塔，调节局部水压和供水。造价低但供水能力有限，适合小区域补充。',
    eff: { pop: 0, jobs: 5, gdp: 2, airPol: 0, waterPol: 0, green: 0, edu: 0, health: 0, safety: 0, power: -3, water: 400, happiness: 0 } },
  reservoir: { name: '水库', cat: 'infrastructure', shortName: '水库', layer: 'ground', cost: 3000, color: '#3d729c', size: 1, desc: '大型蓄水库，供水量最大。同时改善环境和空气质量，提升周边绿化和健康指数。',
    eff: { pop: 0, jobs: 50, gdp: 15, airPol: -3, waterPol: -5, green: 5, edu: 0, health: 2, safety: 1, power: -10, water: 2000, happiness: 5 } },
  desalination: { name: '海水淡化厂', cat: 'infrastructure', shortName: '海水', layer: 'ground', cost: 2500, color: '#2e7d86', size: 1, desc: '海水淡化处理厂，将海水转化为淡水。适合沿海缺水城市，供电消耗大但供水充足。',
    eff: { pop: 0, jobs: 100, gdp: 40, airPol: 1, waterPol: 0, green: 1, edu: 0, health: 0, safety: 0, power: -40, water: 1200, happiness: 1 } },
  fireStation: { name: '消防站', cat: 'infrastructure', shortName: '消防', layer: 'ground', cost: 400, color: '#a83828', size: 1, desc: '消防站，负责火灾应急救援。提升周边治安和安全指数，覆盖范围内灾害损失降低。',
    eff: { pop: 0, jobs: 40, gdp: 5, airPol: 0.3, waterPol: 0, green: 0, edu: 0, health: 0, safety: 10, power: -5, water: -3, happiness: 2 } },
  police: { name: '警察局', cat: 'infrastructure', shortName: '警局', layer: 'ground', cost: 400, color: '#3d5a8c', size: 1, desc: '警察局/派出所，维护社会治安。大幅提升安全指数和居民安全感，同时提升幸福度。',
    eff: { pop: 0, jobs: 50, gdp: 5, airPol: 0.3, waterPol: 0, green: 0, edu: 0, health: 0, safety: 12, power: -5, water: -3, happiness: 3 } },
  govBuilding: { name: '政府大楼', cat: 'infrastructure', shortName: '政府', layer: 'ground', cost: 1000, color: '#5a4820', size: 1, desc: '政府行政办公大楼，城市治理核心。提升行政效率、治安和教育，提供大量公务员岗位。',
    eff: { pop: 0, jobs: 200, gdp: 20, airPol: 1, waterPol: 0.5, green: 0, edu: 2, health: 0, safety: 5, power: -20, water: -10, happiness: 1, admin: 10 } },
  utility: { name: '地下管廊', cat: 'transit', shortName: '管线', layer: 'underground', cost: 300, color: '#3a3a3a', size: 1, desc: '综合地下管廊，集中铺设水电气管线。不占地面空间，提升城市运行效率和居民满意度。',
    eff: { pop: 0, jobs: 0, gdp: 0, airPol: 0, waterPol: 0, green: 0, edu: 0, health: 0, safety: 0, power: 0, water: 0, happiness: 1, utility: 1 } },
  parking: { name: '地下停车场', cat: 'transit', shortName: '停车', layer: 'underground', cost: 200, color: '#2a2a2a', size: 1, desc: '地下停车设施，缓解地面停车压力。不占地面空间，减少空气污染，提升居民便利度。',
    eff: { pop: 0, jobs: 5, gdp: 5, airPol: -1, waterPol: 0, green: 0, edu: 0, health: 0, safety: 0, power: -3, water: 0, happiness: 2 } },
  subwayStation: { name: '地铁站', cat: 'transit', shortName: '地铁', layer: 'subway', cost: 800, color: '#3a6a9c', size: 1, desc: '地铁车站，提供大容量公共交通。大幅提升交通效率和居民出行便利，需配套地铁线路。', requireApproval: 'subwayApproved',
    eff: { pop: 0, jobs: 30, gdp: 20, airPol: 0, waterPol: 0, green: 0, edu: 0, health: 0, safety: 1, power: -10, water: -3, happiness: 5, transit: 20 } },
  subwayLine: { name: '地铁线路', cat: 'transit', shortName: '地铁', layer: 'subway', cost: 150, color: '#2f5884', size: 1, desc: '地铁隧道和轨道。连接地铁站，形成地铁网络。需先获批地铁建设权限才能建造。',
    eff: { pop: 0, jobs: 0, gdp: 0, airPol: 0, waterPol: 0, green: 0, edu: 0, health: 0, safety: 0, power: -2, water: 0, happiness: 2, transit: 5 } },
  elevatedRoad: { name: '高架道路', cat: 'transit', shortName: '高架', layer: 'elevated', cost: 400, color: '#3a4a5a', size: 1, desc: '高架快速路，缓解地面交通拥堵。不占地面通道，提升交通效率但略有视觉污染。',
    eff: { pop: 0, jobs: 0, gdp: 0, airPol: 0.5, waterPol: 0, green: -0.5, edu: 0, health: 0, safety: 0, power: 0, water: 0, happiness: 0, transit: 8 } },
  elevatedRail: { name: '高架轻轨', cat: 'transit', shortName: '轻轨', layer: 'elevated', cost: 600, color: '#1a4a6a', size: 1, desc: '高架轻轨（BRT/单轨），中运量公共交通。比地铁便宜但运力较低，适合中等城市。',
    eff: { pop: 0, jobs: 20, gdp: 15, airPol: 0.3, waterPol: 0, green: 0, edu: 0, health: 0, safety: 0, power: -5, water: 0, happiness: 3, transit: 12 } },
  // v2.2.5c: 轻轨线路（类地铁，单色线条绘制）
  lightRail: { name: '轻轨线路', cat: 'transit', shortName: '轻轨', layer: 'elevated', cost: 250, color: '#16a085', size: 1, desc: '轻轨轨道和线路。中运量公共交通，建设成本约为地铁的1/3，适合中等客流走廊。',
    eff: { pop: 0, jobs: 0, gdp: 0, airPol: 0, waterPol: 0, green: 0, edu: 0, health: 0, safety: 0, power: -1, water: 0, happiness: 1, transit: 8 } },
  // v2.2.5c: 轻轨站点
  lightRailStation: { name: '轻轨站', cat: 'transit', shortName: '轻轨站', layer: 'elevated', cost: 400, color: '#1abc9c', size: 1, desc: '轻轨车站，提供中运量公共交通。比地铁站便宜，运力约为地铁的1/2。只能放置在轻轨线路上。', requireApproval: 'lightRailApproved',
    eff: { pop: 0, jobs: 15, gdp: 10, airPol: 0, waterPol: 0, green: 0, edu: 0, health: 0, safety: 1, power: -5, water: -2, happiness: 3, transit: 10 } },
  // v2.2.5c: 公交站（小型，低容量）
  busStop: { name: '公交站', cat: 'transit', shortName: '公交', layer: 'ground', cost: 50, color: '#e67e22', size: 1, desc: '公交中途站，提供基础公共交通服务。建设成本低，需配合道路使用。每个站点小幅分流路面车流。',
    eff: { pop: 0, jobs: 2, gdp: 2, airPol: -0.5, waterPol: 0, green: 0, edu: 0, health: 0, safety: 0, power: -1, water: 0, happiness: 2, transit: 3 } },
  // v2.2.5c: 公交总站（大型，高容量）
  busTerminal: { name: '公交总站', cat: 'transit', shortName: '公交枢纽', layer: 'ground', cost: 500, color: '#d35400', size: 1, desc: '公交枢纽总站，线路起讫和调度中心。建设成本较高，但分流效果显著，可大幅缓解周边道路拥堵。',
    eff: { pop: 0, jobs: 40, gdp: 15, airPol: -1, waterPol: 0, green: 0, edu: 0, health: 0, safety: 2, power: -8, water: -3, happiness: 4, transit: 15 } },
  airFilter: { name: '空气净化站', cat: 'green', shortName: '净化', layer: 'ground', cost: 500, color: '#1a8a5a', size: 1, desc: '大型空气净化设施，主动过滤空气污染物。大幅降低空气污染指数，改善空气质量。',
    eff: { pop: 0, jobs: 20, gdp: 5, airPol: -35, waterPol: 0, green: 2, edu: 0, health: 4, safety: 0, power: -15, water: -5, happiness: 5 } },
  sewagePlant: { name: '污水处理厂', cat: 'green', shortName: '污水', layer: 'ground', cost: 600, color: '#2e6a94', size: 1, desc: '污水处理设施，净化工业和生活污水。大幅降低水污染，改善水质和居民健康。',
    eff: { pop: 0, jobs: 30, gdp: 8, airPol: 0, waterPol: -40, green: 0, edu: 0, health: 5, safety: 0, power: -12, water: 0, happiness: 5 } },
  ecoWetland: { name: '生态湿地', shortName: '湿地', cat: 'green', layer: 'ground', cost: 300, color: '#2a7a3e', size: 1, desc: '人工生态湿地，自然净化水质和空气。低成本高效净化，同时提升绿化和生物多样性。',
    eff: { pop: 0, jobs: 5, gdp: 2, airPol: -15, waterPol: -20, green: 10, edu: 0, health: 3, safety: 0, power: -3, water: 0, happiness: 7 } },
  noiseBarrier: { name: '隔音屏障', cat: 'green', shortName: '隔音', layer: 'ground', cost: 200, color: '#5a6a7a', size: 1, desc: '隔音降噪设施，安装在噪音源周边。大幅降低噪音污染，提升周边居民生活质量。',
    eff: { pop: 0, jobs: 0, gdp: 0, airPol: -3, waterPol: 0, green: 1, edu: 0, health: 1, safety: 0, power: -5, water: 0, happiness: 6, noise: -20 } },
  wastePlant: { name: '垃圾分类站', cat: 'green', shortName: '垃圾', layer: 'ground', cost: 400, color: '#3a6a2a', size: 1, desc: '垃圾分类回收处理站，减少固体废弃物。降低空气和水污染，提升居民环保意识。',
    eff: { pop: 0, jobs: 25, gdp: 10, airPol: -8, waterPol: -12, green: 2, edu: 0, health: 3, safety: 1, power: -8, water: -3, happiness: 4 } },
  wasteIncinerator: { name: '垃圾焚烧发电厂', cat: 'infrastructure', shortName: '焚烧发电', layer: 'ground', cost: 3000, color: '#5a4a2a', size: 1, desc: '垃圾焚烧发电厂，将城市生活垃圾焚烧发电。既解决垃圾处理问题，又提供电力供应。焚烧产生的废气经净化处理后排放，但对周边空气和居民健康仍有轻微影响。',
    eff: { pop: 0, jobs: 80, gdp: 50, airPol: 4, waterPol: 1, green: 0, edu: 0, health: -1, safety: 0, power: 1800, water: -10, happiness: -2, wasteCap: 80 } },
  // v2.4.7: 交通枢纽建筑
  // 铁路线路单元格（类似地铁线路单元格）
  railwayLine: { name: '铁路', cat: 'transit', shortName: '铁路', layer: 'ground', cost: 60, color: '#5a4a3a', size: 1, desc: '铁路轨道线路。连接火车站，构成铁路运输网络。地图生成时自带横穿地图的铁路。',
    eff: { pop: 0, jobs: 0, gdp: 0, airPol: 0.5, waterPol: 0, green: -0.5, edu: 0, health: 0, safety: 0, power: -2, water: 0, happiness: 0, noise: 3 } },
  // 高铁线路单元格
  hsrLine: { name: '高铁线路', cat: 'transit', shortName: '高铁', layer: 'ground', cost: 100, color: '#1a7ab8', size: 1, desc: '高速铁路轨道线路。连接高铁站，构成高铁运输网络。地图生成时有概率自带横穿地图的高铁。',
    eff: { pop: 0, jobs: 0, gdp: 0, airPol: 0.2, waterPol: 0, green: -0.3, edu: 0, health: 0, safety: 0, power: -3, water: 0, happiness: 1, noise: 2 } },
  // 火车站 — 只能建在铁路线上（GDP/噪音由game-loop.js动态计算，eff中置0避免双重计算）
  railwayStation: { name: '火车站', cat: 'transit', shortName: '火车站', layer: 'ground', cost: 1500, color: '#8B4513', size: 1, desc: '火车站，提供铁路客运和货运服务。必须建在铁路线上。根据城市人口自动划定车站等级（特等站至五等站），可扩建候车室、停车场等配套。',
    eff: { pop: 0, jobs: 100, gdp: 0, airPol: 2, waterPol: 0.5, green: -1, edu: 0, health: 0, safety: 2, power: -20, water: -5, happiness: 3, noise: 0, transit: 15 } },
  // 高铁站 — 只能建在高铁线上（GDP/噪音由game-loop.js动态计算，eff中置0避免双重计算）
  hsrStation: { name: '高铁站', cat: 'transit', shortName: '高铁站', layer: 'ground', cost: 3000, color: '#2196F3', size: 1, desc: '高速铁路车站，提供高铁客运服务。必须建在高铁线上。大幅提升交通效率和GDP，可扩建配套。春运期间客流量激增。',
    eff: { pop: 0, jobs: 150, gdp: 0, airPol: 1, waterPol: 0, green: 0, edu: 0, health: 0, safety: 2, power: -30, water: -8, happiness: 5, noise: 0, transit: 25 } },
  // 机场 — 需审批，航站楼与跑道分开建设（GDP/噪音由game-loop.js动态计算，eff中置0避免双重计算）
  airport: { name: '机场航站楼', cat: 'infrastructure', shortName: '机场', layer: 'ground', cost: 5000, color: '#607D8B', size: 1, desc: '民用机场航站楼。跑道需单独建设，在附近放置跑道后自动关联。根据关联跑道数量和等级划定机场等级（1C至4F）。带来贸易收入，但产生噪音污染。等级超过4D可申报国际机场。', requireApproval: 'airportApproved',
    eff: { pop: 0, jobs: 200, gdp: 0, airPol: 5, waterPol: 0, green: -2, edu: 0, health: 0, safety: 1, power: -40, water: -10, happiness: -2, noise: 0 } },
  // v2.4.8: 跑道 — 独立建设，与附近机场航站楼自动关联
  runway: { name: '机场跑道', cat: 'infrastructure', shortName: '跑道', layer: 'ground', cost: 1500, color: '#3a3a3a', size: 1, desc: '机场跑道，需至少6格直线空地。建成后自动关联最近的机场航站楼，提升机场等级。单条跑道长度决定等级字母（C/D/E/F级），跑道数量决定数字部分。',
    eff: { pop: 0, jobs: 0, gdp: 0, airPol: 0, waterPol: 0, green: 0, edu: 0, health: 0, safety: 0, power: -5, water: 0, happiness: 0, noise: 0 } },
  // 港口码头 — 邻水可建，每图最多2个（GDP/噪音由game-loop.js动态计算，eff中置0避免双重计算）
  port: { name: '港口码头', cat: 'infrastructure', shortName: '港口', layer: 'ground', cost: 2000, color: '#795548', size: 1, desc: '港口码头，提供水路货运和客运服务。只能在邻水区域建设，每个地图最多2个。带来贸易收入和就业。',
    eff: { pop: 0, jobs: 100, gdp: 0, airPol: 3, waterPol: 3, green: -1, edu: 0, health: 0, safety: 1, power: -15, water: 0, happiness: 1, noise: 0 } },
};

const PALETTE_CATEGORIES = [
  { name: '住宅区', items: ['lowRes', 'midRes', 'highRes', 'luxuryRes'] },
  { name: '工业区', items: ['lightInd', 'heavyInd', 'hazInd'] },
  { name: '商业区', items: ['streetCom', 'concCom', 'mixCom', 'plazaCom', 'comStreet', 'comComplex'] },
  { name: '基础设施', items: ['road', 'park', 'elementarySchool', 'middleSchool', 'highSchool', 'hospital', 'fireStation', 'police', 'govBuilding'] },
  { name: '电力设施', items: ['powerPlant', 'gasPower', 'cleanEnergy', 'solarPlant', 'windFarm', 'hydroDam', 'nuclearPlant', 'substation', 'wasteIncinerator'] },
  { name: '供水设施', items: ['waterTower', 'waterPump', 'waterPlant', 'reservoir', 'desalination'] },
  { name: '环保设施', items: ['airFilter', 'sewagePlant', 'ecoWetland', 'noiseBarrier', 'wastePlant'] },
  { name: '地下层', items: ['parking'] },
  // v2.2.7: 公共交通整合板块（地铁层+公共交通合并）
  // v2.4.8: 移除火车站/高铁站（不可建设），添加跑道（与机场分开建设）
  { name: '公共交通', items: ['subwayStation', 'lightRailStation', 'busStop', 'busTerminal', 'airport', 'runway', 'port'] },
];

